### ISSUE TITLE
Allow external file reference for ihm_model_list entries

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#12]
Want to be able to reference an external file for sphere models, both individual models and ensembles.  For the nup84 ChimeraX demo I added a file reference to access the sphere model ensembles (multimodel PDB file) to the ihm_model_list table.

A problem with this is that there are not good formats established for sphere models.  So IMP sometimes uses multi-model PDB files for this.  We have talked about using DCD or other binary trajectory formats for this purpose.  RMF is another format used by IMP for sphere model ensembles. But the actual format of the linked file is not something the IHM dictionary needs to worry about -- it just needs to provide the ability to link to external sphere files in whatever format IMP, Rosetta, or other modeling programs use.

**Comment by tomgoddard** [comment]
Some more details from duplicate ticket #15.

Would like IHM to be able to reference sphere model ensemble files that are too big to be put into the IHM file. Currently the nup84 has such ensembles in the DOI zip archive in PDB format and I hacked references to those files into the nup84 ChimeraX demo by adding a file reference in the ihm_model_list table as follows.

_ihm_model_list.ordinal_id
_ihm_model_list.model_id
_ihm_model_list.model_name
_ihm_model_list.model_group_id
_ihm_model_list.model_group_name
_ihm_model_list.assembly_id
_ihm_model_list.protocol_id
_ihm_model_list.file
1 1 'Cluster 1 best score' 1 'Cluster 1' 1 1 .
2 2 'Cluster 2 best score' 2 'Cluster 2' 1 1 .
3 3 'Cluster 1 ensemble' 1 'Cluster 1' 1 1 extra_data/ensembles/cluster1.pdb
4 4 'Cluster 2 ensemble' 2 'Cluster 2' 1 1 extra_data/ensembles/cluster2.pdb

Instead the link out should be an id to another table that lists all the externally linked files either by DOI+archive path, URL, or local file path. That table would also list the file format -- for instance the sphere model ensembles might be in RMF format (currently used by IMP) or a binary trajectory format.

**Comment by brindakv** [comment]
Added external file reference to the IHM_ENSEMBLE_INFO category.
