### ISSUE TITLE
Use two model groups for clusters 1 and 2 of nup84.cif

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#13]
Would be good to use the model group capability of IHM for cluster 1 and 2 of the nup84 example data.  Also name the two groups "Cluster 1" and "Cluster 2".  This requires changing nup84.cif table

_ihm_model_list.ordinal_id
_ihm_model_list.model_id
_ihm_model_list.model_group_id
_ihm_model_list.model_group_name
_ihm_model_list.assembly_id
_ihm_model_list.protocol_id
1 1 1 'Sphere models' 1 1
2 2 1 'Sphere models' 1 1

to

_ihm_model_list.ordinal_id
_ihm_model_list.model_id
_ihm_model_list.model_group_id
_ihm_model_list.model_group_name
_ihm_model_list.assembly_id
_ihm_model_list.protocol_id
1 1 1 'Cluster 1' 1 1
2 2 2 'Cluster 2' 1 1

Without this there is no indication in the nup84 file that the two sphere models are associated with two clusters.

**Comment by benmwebb** [comment]
Should be addressed by integrativemodeling/nup84@0ddc8d1462; I'll update the example shortly.
