### ISSUE TITLE
Add ihm_localization_density_files to nup84 example

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#17]
Would be good to include references to localization map MRC files in the nup84 example using the new ihm_localization_density_files table.  I think the MRC files in the DOI archive may not align with the sphere models.  I have made new MRC localization files from the ensemble models using Chimera.  We could include those in a new DOI archive in order to make nup84 a better example of the IHM format.

**Comment by tomgoddard** [comment]
Would also like the localization density map table for the mediator and exosome examples.  It looks like the mediator DOI archive has those MRC files.  Exosome has some MRC files but not one for each asym_id.

**Comment by benmwebb** [comment]
> Would be good to include references to localization map MRC files in the nup84 example

Tom, if you can provide me with your new MRC files I can modify the Nup84 mmCIF output to point to them. I don't think it's worth trying to point to the `.dx` files in GitHub for now since they're not aligned anyway.

**Comment by tomgoddard** [comment]
Here are the nup84 localization density maps I made that align with the IHM nup84 example sphere models.

	http://www.cgl.ucsf.edu/home/goddard/temp/nup84_localization.zip

  Tom
