### ISSUE TITLE
Web-browsable IHM dictionary?

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#19]
It might be easier for newcomers to the dictionary if they could browse it with a web browser in the same way as existing extension dictionaries, e.g. something like http://mmcif.wwpdb.org/dictionaries/mmcif_em.dic/Index/. Is there any way to feed the existing draft dictionary into whatever tool generates those views? Ideally that would be automated and update weekly (or whenever the repository is updated) and the data dumped somewhere accessible, such as pdb-dev.

**Comment by brindakv** [comment]
The [I/H methods extension dictionary](http://mmcif.wwpdb.org/dictionaries/mmcif_ihm.dic/Index/) is now available on the [wwPDB mmCIF](http://mmcif.wwpdb.org) website. It can also be [downloaded](http://mmcif.wwpdb.org/dictionaries/downloads.html) from the same site.
