### ISSUE TITLE
List all linked out files in a single new table.

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#2]
In order to use IHM format as a working format while a modeling project is in progress, the externally linked files (comparative models, sequence alignments, EM maps, ensembles of result structures, localization maps, ...) should be listed in a table that refers to local files (on the local disk) instead of referencing a DOI zip archive.

One design would give an integer id to every external file, external database reference, external DOI reference, and all other tables would use this id.  Any external data could be referenced in any of these 3 ways (local file, database, DOI archive).

Having external references in one table will simplify validating that deposited structures do not reference missing data.

**Comment by tomgoddard** [comment]
How does an IHM file reference a local file currently?  For example a sequence alignment file, or localization density local file?  How is a reference to a sequence alignment file using a URL done?

**Comment by brindakv** [comment]
Reference to local file has been added.

**Comment by brindakv** [comment]
A new category (`IHM_EXTERNAL_FILES`) has been added to reference all external files.
