### ISSUE TITLE
SSL certificate for pdb-dev website has expired

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#20]
Looks like the SSL certificate for https://pdb-dev.rcsb.rutgers.edu/ expired on Feb 7th 2017. So anybody trying to visit the page now will get an 'insecure connection' error (I can't see it at all in Firefox without adding an exception). Obviously this is going to put a lot of people off using the website.

**Comment by brindakv** [comment]
This has been fixed.
