### ISSUE TITLE
Need to be more clear about what each "state" is

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#21]
A model containing two states may actually represent a bulk sample of 10<sup>23</sup> molecules, where some fraction of those molecules are in one state (different conformation and/or composition) and some other fraction are in a different state. Alternatively, the experimental data may have been determined from a single molecule experiment, in which case the different states in the model are adopted by the same molecule at different points in time (and the experiment returns some kind of convolution of these states). These two conditions should be distinguished - perhaps with an extra enumeration in the `ihm_multi_state_modeling` table. (An alternative solution would be to require that the latter case be treated as a single state, with multiple time points; the problem here is that since the data are convoluted there is no way to order the states.)

**Comment by brindakv** [comment]
Added _ihm_multi_state_modeling.experiment_type as enumerated list with "Fraction of bulk" and "Single molecule" as options.
