### ISSUE TITLE
Add ihm_external_files.details

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#22]
The old `ihm_dataset_other` category used to have a `details` field. This category is largely replaced now by `ihm_external_files`. Would be useful to have a `details` field in that category so we can give a human-readable description of the file.

**Comment by benmwebb** [comment]
Note that if this *is* added, `ihm_modeling_workflow_files.description` would no longer be necessary.

**Comment by brindakv** [comment]
Dictionary has been updated accordingly. `ihm_external_files.details` and `ihm_external_files.content_type` have been added and `IHM_MODELING_WORKFLOW_FILES` has been removed.
