### ISSUE TITLE
Add references to sphere model ensemble PDB files for nup84, exosome and mediator

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#24]
The ihm_ensemble_info table now has an ensemble_file_id field to reference the ensemble sphere files.  These are in the nup84 example as multimodel PDB files (not sure about mediator and exosome).  Should include reference to these ensemble files in the example data.

**Comment by benmwebb** [comment]
There's no single file containing each ensemble for mediator and exosome (in each case the ensemble is a directory containing a ton of PDB and RMF files - e.g. the first cluster for mediator is [here](https://github.com/integrativemodeling/mediator/tree/master/analysis/clustering/kmeans_weight_500_4/cluster.0)). So I can't easily link out to them unless we can use a directory name or wildcards in external files (I don't think we can, but @brindakv can clarify) or I manually make a separate .zip file for each ensemble (as per #25).

**Comment by brindakv** [comment]
As defined currently, we cannot use directory names or wildcards in the `ihm_external_files` category.

**Comment by tomgoddard** [comment]
I think we should try to provide a reasonable example of how to handle the ensemble sphere models.  Here is my best idea of what would be reasonable.  The ensemble models should be in individual files (e.g. PDB) in a directory, preferably with an padded integer file suffix so their order can be preserved when viewed in ChimeraX.  Since the ensembles are what makes our example DOI archives very large and slow to download, it is probably best if the ensembles are a separate DOI zip file.  Since more than one ensemble can be provided I think they could reasonably put into a single archive in separate subdirectories.  To refer to a specific ensemble in the ihm_external_files could give the file_path as the directory containing the ensemble which holds the individual model files.  Ideally ensembles (cluster 1 or cluster 2) could each be fetched separately.  That is a bigger issue #25 that in general the IHM associated files should be fetchable individually rather than requiring downloading a zip file containing many files that are possibly not of interest.  As a first step putting all ensembles in one zip archive solves a lot of the problem.  Currently the nup84 DOI archive contains a two *.tar.gz ensemble files, one for each of the 2 clusters, and the *.tar.gz contains exactly one multimodel PDB file.  This is just weird — not clear why the authors did not simply use a *.pdb.gz.  The tar file contains no directories.  So the current nup84 ensembles do not fit what I am proposing.   But probably multi-model PDB files should be acceptable, so I think it reasonable to also allow the separate DOI for the ensembles to have cluster1.pdb which is a multimodel file and that file can be referenced in ihm_external_files.

The above ideas of course require creating newl nup84, mediator and exosome archives.  I think part of developing the IHM format is to produce examples with a reasonable organization.  Since our examples are from old projects I think it is unavoidable that the data has to be reorganized to some extent.

**Comment by tomgoddard** [comment]
The nup84 clus.1.pdb.gz DOI archive file has two problems preventing it from being correctly parsed.  First it has ENDMOL records which should be ENDMDL.  Second the MODEL records have a serial number "MODEL   1", but every model in the above file is called 1.  The serial numbers should increment.
