### ISSUE TITLE
Local paths in ihm_external_files.file_path

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#26]
Does `ihm_external_files.file_path` require paths to be separated with `/` or `\` or is either acceptable? Windows builds of our software will naturally output paths separated with `\` while the provided examples all use `/`. The docs say "This data item assumes a POSIX-like directory structure" but I'm not sure if that means "you must use / to separate paths".

For local files, the path is required to be a relative path. But relative to what?

**Comment by tomgoddard** [comment]
I assumed in ChimeraX that any relative path in ihm_external_files.file_path was relative to directory containing the ihm file.

**Comment by brindakv** [comment]
For local supplementary files, the path is relative to master ihm file. I understand restricting to POSIX-like file paths creates problem with Windows builds. We can may be remove that restriction for now.

**Comment by brindakv** [comment]
Yes

**Comment by tomgoddard** [comment]
Better I think to always use /.  ChimeraX does not know what OS the file was written on so won't know whether to expect / or \.
