### ISSUE TITLE
ihm_starting_model_seq_dif.db_entity_id

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#28]
When a starting model differs from the input crystal structure by a MSE -> MET mutation, am I required to add a new entity to the mmCIF file to list the input crystal structure's sequence (with MSE)? I assume that's what `ihm_starting_model_seq_dif.db_entity_id` is for, but the dictionary MSE example has `ihm_starting_model_seq_dif.entity_id` = `ihm_starting_model_seq_dif.db_entity_id`, which surely can't happen if the sequences are different, right?

**Comment by brindakv** [comment]
The `IHM_STARTING_MODEL_SEQ_DIF` category maps out point differences in the sequences of the starting model in a repository (mainly PDB, may be Model Archive) and the starting model used in the integrative modeling. The assumption is that this is not relevant if the starting model in not available in a repository. The `ihm_starting_model_seq_dif.db_entity_id`, `ihm_starting_model_seq_dif.db_asym_id`, `ihm_starting_model_seq_dif.db_seq_id`, or `ihm_starting_model_seq_dif.db_comp_id` do not correspond to the current molecular system. These correspond to the the `entity_id`, `asym_id`, `comp_id` and `seq_id` of the starting model in the repository.

**Comment by benmwebb** [comment]
If I understand you correctly then, I should emit `.` for `ihm_starting_model_seq_dif.db_entity_id` if the starting model came from a `.pdb` file (as is the case for all of our examples - we didn't use `.cif` PDB files) since an entity ID isn't available.

**Comment by brindakv** [comment]
Does the same problem arise with `ihm_starting_model_seq_dif.db_asym_id`, `ihm_starting_model_seq_dif.db_seq_id`, and `ihm_starting_model_seq_dif.db_comp_id` as well?

**Comment by benmwebb** [comment]
No, because that information is available in the `.pdb` file (at least, equivalent information is, assuming no differences between the `.pdb` and `.cif` for a given PDB ID).

**Comment by brindakv** [comment]
Then may be it makes more sense to not have the `db_entity_id` data item at all because the point difference can be still uniquely defined using the `asym_id`, `comp_id` and `seq_id`.

**Comment by brindakv** [comment]
Or we can make it non-mandatory.
