### ISSUE TITLE
content_type for localization density

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#35]
Would be nice to specify the content_type for localization density ".mrc" files in ihm_external_files as "localization density".  Currently for the nup84, exosome, mediator examples it describes the content_type as 'Modeling or post-processing output' which is quite a bit vaguer.

**Comment by benmwebb** [comment]
That's not what `content_type` is for - you want `file_format`. The dictionary covers MRC files. Shouldn't be too difficult to populate this from IMP for some common file types.

**Comment by benmwebb** [comment]
Or if you really want to describe what the data is used for rather than what the format of the file is (maybe I don't understand your question), @brindakv would need to extend the enumeration accordingly. Either way, easy to add support at the IMP end.

**Comment by tomgoddard** [comment]
Sorry I was not clear.  It appears that content_type describes what the contents of the file represents, not the file format, and I think that description would be more useful if it said "localization density".

**Comment by brindakv** [comment]
@benmwebb @tomgoddard, any suggestion on whether we change/expand the enumeration list for `content_type` or we create a separate data item with a different set of enumerations?

**Comment by benmwebb** [comment]
> Sorry I was not clear.  It appears that content_type describes what the contents of the file represents, not the file format, and I think that description would be more useful if it said "localization density".

But isn't that implicit from the fact that `ihm_localization_density_files.file_id` points to it?

**Comment by benmwebb** [comment]
> any suggestion on whether we change/expand the enumeration list

I'd think that just expanding the enumeration is the simplest option.

**Comment by benmwebb** [comment]
Based on our conversation today, sounds like this is for the benefit of humans (since computers can infer the file's purpose based on what links to it). I'll populate `ihm_external_files.details` accordingly in the IMP examples.
