### ISSUE TITLE
Units for ihm_external_files.file_size_kb?

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#36]
The dictionary is unclear what the units are for `ihm_external_files.file_size_kb`. Are "kilobytes" old-style (1024 bytes) or new-style (1000 bytes)? If the former, it would be clearer to say "kibibytes". Either way the multiplier should be stated in the dictionary so it's clear.

**Comment by tomgoddard** [comment]
Maybe making it ihm_external_files.file_size in bytes would be better.
