### ISSUE TITLE
Align ensemble models to match localization density for nup84

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#37]
The current nup84 example ensemble models seem to be positioned with random orientations.  This is not good for visualization.  Our examples should encourage others to follow best practices, and I think in this case the ensemble models should be aligned in whatever way they were aligned when computing the localization density maps.  There are at least 2 different possible reasonable alignments, either aligning all beads (with equal weighting per bead) to minimize RMSD, or align only chains A, E, G which were held fixed in the ensemble calculation.  I believe we are using the localization density maps I computed using the first alignment choice.  I can probably write the new DCD files if this is deemed reasonable.  ChimeraX has options to do the alignments on the fly, but it is a real nuisance to use those options.

**Comment by benmwebb** [comment]
Well, that's the data that was generated. But I agree it would be nice to have ensembles that are aligned with the localization densities, so if you're happy to generate them, send them my way and I'll add them to the Zenodo DOI.

**Comment by tomgoddard** [comment]
Hi Ben,

  Here are nup84 ensemble coordinates in DCD format where I’ve aligned each ensemble member to the best scoring model.  Could you update the nup84 example DCD coordinates to use these?  These aligned coordinates are what was used to compute the localization densities for nup84.

http://www.cgl.ucsf.edu/home/goddard/temp/cluster.1.dcd <http://www.cgl.ucsf.edu/home/goddard/temp/cluster.1.dcd>
http://www.cgl.ucsf.edu/home/goddard/temp/cluster.2.dcd <http://www.cgl.ucsf.edu/home/goddard/temp/cluster.2.dcd>

  Tom
