### ISSUE TITLE
Need permanent identifiers/accessions for PDB-dev entries

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#39]
The dictionary is now at the point where we can usefully encode entire structures. We and other labs would like to start depositing structures in PDB-dev in future publications. In order for this to work effectively, we'll need to be able to uniquely refer to a deposit - so we'll need some sort of permanent identifier or accession code.

**Comment by brindakv** [comment]
The PDB-Dev accession codes will be of the form PDBDEV_XXXXXXXX.
