### ISSUE TITLE
Use full file paths within DOI archives

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#4]
Currently the ihm_dataset_other fields "doi" and "content_filename" are used to refer to a DOI of a zip archive and a file within that archive.  In our nup84, mediator and exosome example data the currently supplied content_filename is not actually the full path within the zip archive -- it excludes the top level directory listed in the archive.  In the nup84 example data the "content_filename" is given, for example, as "data/ScNup84_7-488_506-726_new.pdb", but the actual path in the archive is "integrativemodeling-nup84-a69f895/data/ScNup84_7-488_506-726_new.pdb".  Currently the top level directory is not being included because it is technically difficult to determine in an automated fashion according to Ben Webb.  That top level directory name includes the GitHub repository version string and is automatically included in an upload to Zenodo.  These details are specific to current Sali lab practices and should not alter the fact that "content_filename" should always be a full path to a file in the referenced archive.

**Comment by tomgoddard** [comment]
The nup84, mediator, and exosome example IHM files should be changed to list the full paths within the archives.

**Comment by benmwebb** [comment]
Should be resolved by 47bb7b7b.
