### ISSUE TITLE
Predicted Contacts

### ISSUE THREAD

**Issue by rub1k** [ihmwg/IHM-dictionary#41]
Predicted residue-residue contacts are another commonly used form of distance restraints, like crosslinks. They are commonly used together with crosslinks in integrative modeling. I cannot find explicit support for them in the current form of the dictionary - should general_distance_constraints from the NMR-Star dictionary be used for that? Are they compatible with the IHM dict? Can multiple extensions be used together? Sorry if that is obvious, I'm not so deep into mmCIF yet :)
Best, 
Lukas

**Comment by brindakv** [comment]
Thank you for raising this issue. Predicted residue-residue contacts are handled as part of the [modeling dictionary](https://github.com/JuergenHaasSIB/modeling_dictionary) extension, which is currently under development. Considering the complexities involved in the representation of multi-scale models, we also plan to incorporate definitions for predicted residue-residue contacts in the integrative/hybrid methods dictionary extension. We will update this issue once it is implemented.

**Comment by brindakv** [comment]
[CASP RR format](http://www.predictioncenter.org/casp8/index.cgi?page=format#RR) is an example of a typically used format for predicted residue-residue contacts.

**Comment by brindakv** [comment]
The dictionary has been updated to include predicted contacts. @rub1k please verify if the new category `ihm_predicted_contact_restraint` sufficiently captures the information that you require.

**Comment by rub1k** [comment]
I can verify the new category is exactly what we needed!

**Comment by amjjbonvin** [comment]
This would be thus the way to list predicted contacts from co-evolution analysis I assume.

**Comment by rub1k** [comment]
Yes, exactly!
