### ISSUE TITLE
What is recommended usage for model groups?

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#43]
In David Castillo's fly genome model final_2L_60_161.ihm he uses group id 1 for "Centroid cluster 1" consisting of one model and group id 2 for "Cluster 1" which contains 505 models of an ensemble all specified in the sphere_obj_site table.  This seems reasonable to use 2 groups for these two conceptually distinct collections of models.  In nup84, exosome and mediator examples a single group id is used for "Best scoring model cluster 1" with a single sphere model in the ihm file, and the Cluster 1 ensemble which is a reference to an external DCD file.  This provides two levels of grouping.  The best scoring model is grouped with the ensemble, and the ensemble itself is a different kind of grouping.  But that two levels of grouping cannot be done in the fly genome example because the ensemble models are not in an external file.  The fly genome file currently does not have a ihm_ensemble_info table.  If one was added it would have to specify a single group id and if the group id included both centroid and 505 ensemble models then the centroid would be considered one of the ensemble models which seems wrong.  So a single group id for centroid and ensemble does not seem to work in the fly genome case but is used in the nup84, exosome, mediator cases.  It seems the fly genome example should contain an ihm_ensemble_info table and two separate groups should be used (as in the current file) so that the ihm_ensemble_info can properly refer only to the ensemble members.

The nup84, exosome and mediator cases may be different in that the "Best scoring model" I think actually is one of the ensemble members.  Those examples currently define the ensemble using a group that contains both the best scoring model and the ensemble of models.  Technically this would appear to make the best scoring model appear two times in the ihm_ensemble, once from the sphere_obj_site table and once from the external DCD file for the ensemble models.  This does not seem ideal.

**Comment by brindakv** [comment]
An ensemble of models and its representative can either be grouped together or can be separate groups in the `ihm_model_list` table. The dictionary allows for both. The new data category `ihm_model_representative` identifies the representative and the selection criteria applied (similar to [`pdbx_nmr_representative`](http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/pdbx_nmr_representative.html) category in the PDBx/mmCIF dictionary). The choice between the two options should be decided based on how the modeling was carried out and how the representative was chosen. If the representative is a member of the ensemble (i.e., best scoring model), then it is recommended that the representative and the ensemble belong to the same model group. If the representative is calculated from the ensemble (i.e., centroid), then it is recommended that the representative be separated into a different group.
