### ISSUE TITLE
How is distance_threshold interpreted in ihm_cross_link_restraint table?

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#45]
David Castillo notes that the fly genome example final_2L_60_161.ihm uses 3 types of crosslink restraints with different interpretations of the distance_threshold field in the ihm_cross_link_restraint table:

"These are the restraints we use for our modelling

​LowerBoundHarmonic
  IMP.core.HarmonicLowerBound where the restraint is satisfied if the distance between the particles is above a distance threshold.

UpperBoundHarmonic
  IMP.core.HarmonicUpperBound where the restraint is satisfied if the distance between the particles is below a distance threshold.

Harmonic
  IMP.core.Harmonic where the restraint is satisfied if the distance between the particles is equal to the equilibrium distance "

In order to color violated restraints differently from satisfied restraints in ChimeraX, these different interpretations of the distance_threshold would need to be encoded in the IHM file.

**Comment by brindakv** [comment]
A new data item, `_ihm_cross_link_restraint.restraint_type`, has been added to the dictionary to address this issue.
