### ISSUE TITLE
How to document interface mapping information

### ISSUE THREAD

**Issue by amjjbonvin** [ihmwg/IHM-dictionary#46]
Information about interfaces can be used in the modelling (e.g. by HADDOCK). This can be for examples:
- mutations shown to disrupt the binding
- footprinting experiments for DNA/RNA
- H/D exchange data from MS or NMR
- NMR chemical shift perturbations
- oxidation protection (e.g. detected by MS)
and many others.  

Basically those will provide lists of residues that are expected to be part of the interface. This info is typically not stores in dedicated databases and should be captured here.

**Comment by brindakv** [comment]
Thank you for raising this issue. If you could provide us with some examples of how HADDOCK uses this information as restraints in modeling, we would be able to address it in the dictionary.

**Comment by amjjbonvin** [comment]
This kind of information can be given to HADDOCK as a simple list of residue numbers. The HADDOCK server will translate those into highly ambiguous interactions restraints (similar to ambiguous distances in NMR structure calculations), but with a level of ambiguity with is way larger.  Basically an effective distance restraint is defined between one residue on one protein, and all define residues on the other protein. The effective distance in the restraints is the inverse sixth root of the 1/r**6 sum of all atomic distances between those residues. Effectively the server will translate it into an Xplor/CNS type of format. Here is an example:

! HADDOCK AIR restraints for 1st partner
!
assign ( resid 38  and segid A)
       (
        ( resid 15  and segid B)
     or
        ( resid 16  and segid B)
     or
        ( resid 17  and segid B)
     or
        ( resid 20  and segid B)
     or
        ( resid 48  and segid B)
     or
        ( resid 51  and segid B)
     or
        ( resid 52  and segid B)
       )  2.0 2.0 0.0

In principle, given a list of residues, such a restraint file can be easily generated (e.g. from https://milou.science.uu.nl/services/GenTBL/ ). So simply allowing to define a list of residues should be enough. Those residues can come from mutagenesis, footprinting experiments, or any kind of methodology that will provide such information.  This can even be in some cases predicted interfaces from bioinformatics analysis. 

In the way we are using this info as restraints, the corresponding residues should be making a contact with the defined interface on the other molecules, without defining what the exact contact should be.

So ideally we might want to associate with each defined residue its origin, e.g. is it from mutagenis, NMR mapping, footprinting or whatever... 

I hope this makes sense. Otherwise we can Skype about this.
