### ISSUE TITLE
Need for a more generic distance information class

### ISSUE THREAD

**Issue by amjjbonvin** [ihmwg/IHM-dictionary#47]
The model now allows for cross-link data to be stored. But this is rather specific. In principle any kind of distance should be store, coming from MS or any other experimental method providing such information (e.g. FRET, DEER, ...)

**Comment by brindakv** [comment]
Thank you for raising this issue. We recently discussed this issue in one of our weekly meetings (please refer to the meeting summary [here](https://github.com/ihmwg/IHM-dictionary/wiki/IHM-Meeting-Summary-Sep-21-2017)). As you can see in the meeting summary, the discussion was focused on whether we can decouple the method-specific details from the interpretation of the distance restraints. It was not possible to do that with the crosslinking examples that we had at the time and therefore, the crosslinking categories are specific. 
If you could provide us with some applications of distance restraints derived from FRET, DEER or other experimental methods as examples, we would be able address these requirements in the dictionary.

**Comment by amjjbonvin** [comment]
A simple distance definition would work, e.g. like:

(selection 1) (selection 2) <lower distance limit> <upper distance limit>

Note that the selection can be a single atom, but also a group of atoms to allow for ambiguity.

Some categories might be more specific, probably assuming some kind of (gaussian) distribution of distances and requiring a target distance and some standard deviation. But in first instance I would keep things simple.

**Comment by amjjbonvin** [comment]
And in principle there is nothing special about MS cross-links... These seems to me rather generic distances.

**Comment by brindakv** [comment]
Preliminary definitions for [generic distance restraints](https://github.com/ihmwg/IHM-dictionary/blob/master/generic_distance_restraint.dic) are available in a separate file and will be merged with the [IHM dictionary,](https://github.com/ihmwg/IHM-dictionary/blob/master/ihm-extension.dic) once finalized.
