### ISSUE TITLE
Clarify docs for ihm_starting_model_details.starting_model_sequence_offset

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#50]
It isn't clear from the dictionary docs how `ihm_starting_model_details.starting_model_sequence_offset` is supposed to be interpreted.

Currently I assume it means the same as the IMP definition, which is `I/H model residue # = starting model residue # + offset`

However, it could just as easily mean `starting model residue # =  I/H model residue # + offset`

Easy enough to modify IMP if the second meaning is intended.

**Comment by brindakv** [comment]
This issue has been addressed in the latest dictionary update.
