### ISSUE TITLE
Add possibility to reference a paper from which restraints have been used for the modelling

### ISSUE THREAD

**Issue by mtrellet** [ihmwg/IHM-dictionary#54]
We often face modelling challenges where the data used to derive restraints are coming from a published paper without data being deposited in a particular dataset (e.g. mutagenesis data, DNA footprinting, etc.).
At this moment, the IHM extension does not allow to reference such restraints in a proper way. Possibility to extend the dictionary to add paper DOI as a source of data would be a very nice adding to the dictionary extension.

**Comment by brindakv** [comment]
This has been addressed in the recent update. @mtrellet, please verify that this addresses the requirement adequately.
