### ISSUE TITLE
Indicate missing residues in the model?

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#57]
We'd like to indicate that some residues in our IHM model weren't modeled because insufficient data were available to constrain their position. We've implicitly done this by simply not listing them in `ihm_model_representation` or `ihm_sphere_obj_site`, but should we make this explicit? This roughly corresponds to traditional PDB "residues not observed in the experiment" (`REMARK 465`). Does it make sense for us to populate the mmCIF equivalent, which looks like `pdbx_unobs_or_zero_occ_residues`?

**Comment by amjjbonvin** [comment]
Interesting question... I would say yes since the presence of those in the modelling might be important for the final model even if at the end they are not really defined.

**Comment by benmwebb** [comment]
Just to be clear, it's straightforward to see *which* residues are missing (because no coordinates are available for them) but we want to say *why* they are missing, not just that we 'forgot' to include them. An enumeration for this might include options such as

 - Models too variable (e.g. poor precision over the entire cluster). We can speculate that this is due to insufficient experimental data (poorly constrained)
 - No models found that adequately satisfy all data. We can speculate that this is due to conflicting data, maybe due to noise or heterogeneity, and may indicate a need to do multi-state modeling.

**Comment by brindakv** [comment]
@benmwebb This has been addressed in the latest update.
