### ISSUE TITLE
Allow creating distance restraints to geometric features

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#58]
We can currently store in the dictionary that a residue was restrained to be a certain distance from another residue. However, in our IMP models we often restrain the distance between a residue and an absolute point in space, an axis, a plane, or some other geometric feature. For example, in our models of nuclear pores, we typically orient the system so that the pore aligns with the z axis and the membrane lies in the xy plane. We can then restrain a protein to lie on the nuclear side of the complex (below the xy plane), the cytoplasm side (above the xy plane), or towards the membrane (distance from the surface of a half torus lying in the xy plane, as in the grey region at https://salilab.org/img/gallery/image16_full.gif).

We would like to be able to
 - define these features in the mmCIF file with names
 - show that certain residues are restrained to the features
 - visualize the features in ChimeraX

**Comment by brindakv** [comment]
@benmwebb Please check the [geometric object spatial restraint](https://github.com/ihmwg/IHM-dictionary/blob/master/geometric_object_restraints.dic) definitions and suggest any revisions required.

**Comment by benmwebb** [comment]
Looks good to me so far. I'll have a go at updating the NPC output to use them and see if I run into any problems.

**Comment by brindakv** [comment]
This has been addressed in the recent dictionary update.
