### ISSUE TITLE
Add hyperlinks from PDB-Dev website to raw data

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#59]
The PDB-Dev website currently links to the mmCIF file itself (allowing visualization in ChimeraX) and the accompanying publication. However, there currently is a good deal of data in the mmCIF file which isn't visualized in ChimeraX (such as links to input scripts, raw data not in repositories, experimental data not currently handled by ChimeraX) and so isn't visible to a casual user (who isn't going to load the mmCIF file in a text editor and search for it). It would be useful to extract any such  DOIs from the mmCIF file and display them as hyperlinks on the PDB-Dev website. For example, the Nup84 entry in PDB-Dev should link to its [Zenodo entry](https://zenodo.org/record/820724).

**Comment by brindakv** [comment]
Thanks for pointing it out. This has been implemented.
