### ISSUE TITLE
PDBDEV_00000002.cif entity RPL3 with asym_id "."

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#63]
PDBDEV_00000002.cif lists entity RPL3 with asym_id "." in the ihm_struct_assembly table.  Is this allowed?  According to mmCIF docs "The question mark (?) is used to mark an item value as missing. A period (.) may be used to identify that there is no appropriate value for the item or that a value has been intentionally omitted."  I think there are no coordinates for this entity in the deposited entry but it is listed as a member of an assembly and it is listed in ihm_cross_link_list.

Having no asym_id is inconvenient in ChimeraX because the asym_id is used for referring to objects.  So the crosslink to RPL3 cannot be noted in ChimeraX because it has no asym_id.

**Comment by benmwebb** [comment]
> PDBDEV_00000002.cif lists entity RPL3 with asym_id "." in the ihm_struct_assembly table. Is this allowed?

Sure, this is part of the system that is seen in the experiment, but not modeled, so there's no asym unit for it (and certainly allowed - I checked with Brinda at the time). You can just ignore these crosslinks since they can't be visualized anyway.
