### ISSUE TITLE
Annotate vector and matrix fields as such in _item_sub_category.id

### ISSUE THREAD

**Issue by arose** [ihmwg/IHM-dictionary#64]
Hi,

I am writing a cif-dictionary-to-typescript-code generator for [Mol*](https://molstar.org) and found that there are a couple of vector or matrix containing fields that are not annotated as such via _item_sub_category.id. I am currently looking for square brackets to determine vector/matrix fields but it would be better to just rely on the dictionary itself.

_ihm_2dem_class_average_fitting.rot_matrix[1][1] should have 'matrix' _item_sub_category.id
_ihm_2dem_class_average_fitting.rot_matrix[2][1] should have 'matrix' _item_sub_category.id
_ihm_2dem_class_average_fitting.rot_matrix[3][1] should have 'matrix' _item_sub_category.id
_ihm_2dem_class_average_fitting.rot_matrix[1][2] should have 'matrix' _item_sub_category.id
_ihm_2dem_class_average_fitting.rot_matrix[2][2] should have 'matrix' _item_sub_category.id
_ihm_2dem_class_average_fitting.rot_matrix[3][2] should have 'matrix' _item_sub_category.id
_ihm_2dem_class_average_fitting.rot_matrix[1][3] should have 'matrix' _item_sub_category.id
_ihm_2dem_class_average_fitting.rot_matrix[2][3] should have 'matrix' _item_sub_category.id
_ihm_2dem_class_average_fitting.rot_matrix[3][3] should have 'matrix' _item_sub_category.id
_ihm_2dem_class_average_fitting.tr_vector[1] should have 'vector' _item_sub_category.id
_ihm_2dem_class_average_fitting.tr_vector[2] should have 'vector' _item_sub_category.id
_ihm_2dem_class_average_fitting.tr_vector[3] should have 'vector' _item_sub_category.id
_ihm_gaussian_obj_site.covariance_matrix[1][1] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_site.covariance_matrix[1][2] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_site.covariance_matrix[1][3] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_site.covariance_matrix[2][1] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_site.covariance_matrix[2][2] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_site.covariance_matrix[2][3] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_site.covariance_matrix[3][1] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_site.covariance_matrix[3][2] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_site.covariance_matrix[3][3] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_ensemble.covariance_matrix[1][1] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_ensemble.covariance_matrix[1][2] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_ensemble.covariance_matrix[1][3] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_ensemble.covariance_matrix[2][1] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_ensemble.covariance_matrix[2][2] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_ensemble.covariance_matrix[2][3] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_ensemble.covariance_matrix[3][1] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_ensemble.covariance_matrix[3][2] should have 'matrix' _item_sub_category.id
_ihm_gaussian_obj_ensemble.covariance_matrix[3][3] should have 'matrix' _item_sub_category.id
_ihm_geometric_object_transformation.rot_matrix[1][1] should have 'matrix' _item_sub_category.id
_ihm_geometric_object_transformation.rot_matrix[2][1] should have 'matrix' _item_sub_category.id
_ihm_geometric_object_transformation.rot_matrix[3][1] should have 'matrix' _item_sub_category.id
_ihm_geometric_object_transformation.rot_matrix[1][2] should have 'matrix' _item_sub_category.id
_ihm_geometric_object_transformation.rot_matrix[2][2] should have 'matrix' _item_sub_category.id
_ihm_geometric_object_transformation.rot_matrix[3][2] should have 'matrix' _item_sub_category.id
_ihm_geometric_object_transformation.rot_matrix[1][3] should have 'matrix' _item_sub_category.id
_ihm_geometric_object_transformation.rot_matrix[2][3] should have 'matrix' _item_sub_category.id
_ihm_geometric_object_transformation.rot_matrix[3][3] should have 'matrix' _item_sub_category.id
_ihm_geometric_object_transformation.tr_vector[1] should have 'vector' _item_sub_category.id
_ihm_geometric_object_transformation.tr_vector[2] should have 'vector' _item_sub_category.id
_ihm_geometric_object_transformation.tr_vector[3] should have 'vector' _item_sub_category.id

**Comment by brindakv** [comment]
Fixed in the latest update.

**Comment by arose** [comment]
Thanks!
