### ISSUE TITLE
PDBDEV_00000001.cif has incorrect ihm_external_files data

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#68]
PDBDev entry 01 fails to open in ChimeraX giving an unknown file type error because of incorrect data in the ihm_external_files table.  Specifically ihm_external_files rows 29-35 which are localization map files have reference_id 2 (in column 2) and instead it should be reference_id 5.  Reference id 2 in defined in ihm_external_reference_info is https://zenodo.org/record/1218053/files/clus.1.aligned.dcd while reference id 5 is where the localization map files are found.

Entry validation should certainly verify that all external files exist.

**Comment by tomgoddard** [comment]
Has the fix to PDBDev 01 been pushed to the PDBDev web site?  Kai Kammer reports it still does not open in ChimeraX.

**Comment by brindakv** [comment]
Yes, it is updated now.
