### ISSUE TITLE
Support DSSO crosslinkers

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#71]
In a [recent study](https://www.ncbi.nlm.nih.gov/pubmed/28821611) we used the [DSSO crosslinker](https://www.thermofisher.com/order/catalog/product/A33545) but this is not currently supported by the dictionary. Can you add DSSO (disuccinimidyl sulfoxide) to the `ihm_cross_link_list.linker_type` enumeration?

**Comment by brindakv** [comment]
This issue has been addressed in the latest dictionary update.
