### ISSUE TITLE
What are the valid mappings between ihm_model_representation and atom/sphere_obj site?

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#75]
@brindakv I want python-ihm to sanity-check its output of atom or sphere objects to make sure they match the representation (ihmwg/python-ihm#24). Just wanted to check that I'm reading the dictionary correctly.

If a given `seq_id` range is solely represented by a row in the `ihm_model_representation` table with `granularity=by-atom`, am I correct in thinking that the only valid way to show coordinates for any `seq_id` in this range would be in the `atom_site` table (i.e. no spheres) ?

If `granularity=by-residue`, I could have an entry in `ihm_sphere_obj_site` where `seq_id_begin=seq_id_end` and falls within the range of the representation (i.e. 1-residue beads) but multi-residue beads or `atom_site` entries aren't OK, right?

If `granularity=multi-residue`, I could have an entry in `ihm_sphere_obj_site` where the seq_id range matches that of the representation exactly (i.e. one bead representing the entire range) but no beads of any other size or `atom_site` entries.

If `granularity=by-feature`, entries in `ihm_sphere_obj_site` with any seq_id range and of any size are OK as long as they fall within the range of the representation, but no atoms (I guess technically the number of beads should match `ihm_model_representation.model_object_count` but I probably won't enforce that in the library).

Did I get all of this right?

**Comment by brindakv** [comment]
@benmwebb, see answers in bold below. 

If a given `seq_id` range is solely represented by a row in the `ihm_model_representation` table with `granularity=by-atom`, am I correct in thinking that the only valid way to show coordinates for any `seq_id` in this range would be in the `atom_site` table (i.e. no spheres) ?

**Thats right. However, the same `seq_id` range can have multiple representations identified using different `_ihm_model_representation.representation_id`.** 

If granularity=by-residue, I could have an entry in ihm_sphere_obj_site where seq_id_begin=seq_id_end and falls within the range of the representation (i.e. 1-residue beads) but multi-residue beads or atom_site entries aren't OK, right?

**Yes, the residues in the given `seq_id` range have to be single residue beads. The same caveat as above applies.** 

If granularity=multi-residue, I could have an entry in ihm_sphere_obj_site where the seq_id range matches that of the representation exactly (i.e. one bead representing the entire range) but no beads of any other size or atom_site entries.

**Yes, the residues in the given `seq_id` range have to be represented by one bead representing the entire range. The same caveat as above applies.** 

If granularity=by-feature, entries in ihm_sphere_obj_site with any seq_id range and of any size are OK as long as they fall within the range of the representation, but no atoms (I guess technically the number of beads should match ihm_model_representation.model_object_count but I probably won't enforce that in the library).

**`granularity=by-feature` allows for a given `seq_id` range to be represented by a combination of coarse grained objects including single or multiple residue beads (of varying sizes) described in `ihm_sphere_object_site` category or blobs described in `ihm_gaussian_obj_site` category. No atoms are allowed.**
