### ISSUE TITLE
Extend _ihm_ensemble_info.ensemble_clustering_method enumeration

### ISSUE THREAD

**Issue by benmwebb** [ihmwg/IHM-dictionary#81]
The list of allowed clustering methods in `_ihm_ensemble_info.ensemble_clustering_method` is a little short - essentially just k-means and hierarchical clustering. Add some other methods, such as `Density based threshold-clustering` used in recent IMP applications from @shruthivis such as [γTuSC-Spc110](https://salilab.org/gtuscSpc110). Or perhaps add a `_ihm_ensemble_info.ensemble_clustering_method_other_details` or similar rather than using the `_ihm_ensemble_info.details` data item.

**Comment by brindakv** [comment]
Addressed in v1.18.
