### ISSUE TITLE
Identify whether ensembles are structurally aligned

### ISSUE THREAD

**Issue by brindakv** [ihmwg/IHM-dictionary#84]
Add data item to identify if the models in the ensembles provided by depositors are structurally aligned.

**Comment by aozalevsky** [comment]
It looks like `_ihm_ensemble_info` is the best place to do that. Also, while the terms `structural alignment`, `superposition`, and `superimposition` are used interchangeably, I think `superimposed`  is the best choice.

**Comment by brindakv** [comment]
Addressed in v1.18.
