### ISSUE TITLE
Add AlphaFoldDB to the list of databases

### ISSUE THREAD

**Issue by aozalevsky** [ihmwg/IHM-dictionary#87]
We don't have a definition for the AlphaFoldDB in the `ihm_dataset_related_db_reference.db_name`

**Comment by brindakv** [comment]
Done.

**Comment by aozalevsky** [comment]
@benmwebb can you add a corresponding class to `ihm.location`?

**Comment by benmwebb** [comment]
> @benmwebb can you add a corresponding class to `ihm.location`?

Done in ihmwg/python-ihm@46ef350
